### ISSUE TITLE
为什么这个工程帧数这么高400-500帧

### ISSUE THREAD

**Issue by yogioh123456** [zpzsoft/ShadowMap#1]
看了下，开了Rotate旋转就高，关了就降下来了，不过不知道为啥

**Comment by sgf** [comment]
> 
> 
> 看了下，开了Rotate旋转就高，关了就降下来了，不过不知道为啥

我是从你写的博客过来的。 我觉得它的FPS之所以高，是因为场景过于简单。包括摄像机的角度问题。
